AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  static-site

  Sample SAM Template for static-site

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  EnvironmentType:
    Description: Environment Type
    Type: String

Conditions:
  EnvironmentNotProd: !Not [ !Equals [ !Ref EnvironmentType, "production" ] ]
  EnvironmentProd: !Equals [ !Ref EnvironmentType, "production" ]
  EnvironmentInt: !Equals [ !Ref EnvironmentType, "int" ]

Resources:

  rateApprovalBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'rate-approval-${EnvironmentType}-${AWS::AccountId}-${AWS::Region}'
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: rateApproval.html
        ErrorDocument: Error404.html
      Tags:
        - Key: Service
          Value: hawkgirl
        - Key: Owner
          Value: neutrons
        - Key: Department
          Value: Product
        - Key: Stage
          Value: None

  cloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for rate approval redirection bucket'

  rateApprovalBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'rateApprovalBucket'
      PolicyDocument:
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          Effect: Allow
          Principal:
            AWS: !Join [ '', [ 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ', !Ref cloudFrontOriginAccessIdentity ] ]
          Action: s3:GetObject
          Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref 'rateApprovalBucket', /* ] ]

  
  rateApprovalDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      Fn::Transform:
        Name: "GetSSMParameter"
        Parameters:
          parameterName: KSF-Wildcard-SSL-Certificate
      DistributionConfig:
        Enabled: 'true'
        DefaultRootObject: rateApproval.html
        Aliases:
          - !If
            - EnvironmentProd
            - !Sub "rateapproval.creditsaison.in"
            - !If
              - EnvironmentInt
              - !Join [ "", [ "rateapproval", ".", !Ref EnvironmentType, ".creditsaison.in" ] ]
              - !Join [
                "",
                [ "rateapproval", ".", !Ref EnvironmentType, ".creditsaison.xyz" ],
              ]
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: 'sni-only'
          AcmCertificateArn: "$$KSF-Wildcard-SSL-Certificate$$"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: !Sub 'rate_approval_bucket origin'
          ViewerProtocolPolicy: https-only
        Origins:
          - DomainName: !Join [ '', [ !Ref 'rateApprovalBucket', '.s3.amazonaws.com' ] ]
            Id: !Sub 'rate_approval_bucket origin'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${cloudFrontOriginAccessIdentity}'
        CustomErrorResponses:
          - ErrorCode: '403'
            ResponsePagePath: "/rateApproval.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '300'
          - ErrorCode: '404'
            ResponsePagePath: "/rateApproval.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '300'
          - ErrorCode: '500'
            ResponsePagePath: "/rateApproval.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '300'
      Tags:
        - Key: Service
          Value: hawkgirl
        - Key: Owner
          Value: neutrons
        - Key: Department
          Value: Product
        - Key: Stage
          Value: None


  R53DnsRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt [ rateApprovalDistribution, DomainName ]
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: !Sub "DNS Record for rate approval redirection"
      HostedZoneName: !If
        - EnvironmentProd
        - "creditsaison.in."
        - !If
          - EnvironmentInt
          - !Join [ "", [ !Ref EnvironmentType, ".creditsaison.in." ] ]
          - !Join [ "", [ !Ref EnvironmentType, ".creditsaison.xyz." ] ]
      Name: !If
        - EnvironmentProd
        - !Sub "rateapproval.creditsaison.in"
        - !If
          - EnvironmentInt
          - !Join [ "", [ "rateapproval", ".", !Ref EnvironmentType, ".creditsaison.in" ] ]
          - !Join [
            "",
            [ "rateapproval", ".", !Ref EnvironmentType, ".creditsaison.xyz" ],
          ]
      Type: A



Outputs:
  BucketName:
    Value: !Ref 'rateApprovalBucket'
    Description: Name of S3 bucket to hold website content
  CloudfrontEndpoint:
    Value: !Ref rateApprovalDistribution
    Description: Endpoint for Cloudfront distribution
